# Use root/example as user/password credentials
version: '3.1'

services:

  frontend:
    image: bir_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3001:3000

  backend:
    image: bir_backend
    restart: always
    ports:
      - 4343:4343

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin_password
      ME_CONFIG_MONGODB_SERVER: mongo

  