name: "Create Images"
on: 
    push:
        branches:
            - cluster
jobs:
    create_images_job:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkouts the repository"
              uses: actions/checkout@v4

            - name: "Build the Docker image"
              run: |
                
                # build the image for the frontend
                docker build -t theoafactor/clusterbik:first_test3 frontend/

            - name: "Logs into the Docker registry"
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}


            - name: "Pushes the image to the Docker registry"
              run: |
                #  Pushes this code to the Docker registry
                docker push theoafactor/clusterbik:first_test3 

            - name: "Setup Kubectl"
              uses: azure/setup-kubectl@v2.0
              with: 
                version: "v1.23.6"
              id: install

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with: 
                aws-region: "eu-west-2"
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

            - name: "Setup the cluster"
              run: |
                aws eks update-kubeconfig --name testcluster 

            - name: "Install Helm for this cluster"
              uses: azure/setup-helm@v4.2.0
              id: install-helm

            - name: "Install the helm charts"
              run: |
                
                ## set up the helm chart and pass some configration variables

                helm upgrade --install bik bik -f .values.yaml --set image.tag=3
              

                
            - name: "All set, might be time to pull the image into a cluster"
              run: |
                echo "Pulls the image into a cluster"



            

                
