name: "Simple Deploy for Books I Read"
on:
    push:
        branches:
            - development
            
jobs: 
    Development:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Generate Random number"
              run: |
                echo "APP_VERSION=${RANDOM}" >> $GITHUB_ENV
                # echo "REP_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> GITHUB_ENV

            - name: "Build the Docker Image"
              run: docker build -t theoafactor/simpleweb:${{ env.APP_VERSION }} frontend


            - name: "Login to Docker Hub"
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: "Push the Docker image built to Docker Hub"
              run: |
                docker push theoafactor/simpleweb:${{ env.APP_VERSION }}

            - name: "Setup AWS"
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                aws-region: "eu-west-2"
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

            - name: "Get kubectl"
              uses: azure/setup-kubectl@v3
              with: 
                version: "v1.19.3"
              id: install-kubectl 


            - name: 'Connect to the Cluster'
              run: |
                aws eks update-kubeconfig --name testcluster

            - name: "Install Helm"
              uses: azure/setup-helm@v4.2.0
              id: install-helm

              

