name: Simple App Deployment
on: 
    push: 
      branches: 
        - tests

jobs: 
  testdeployment:
    runs-on: ubuntu-latest
    steps: 
      - name: "Greetings"
        run: |
          echo "--- Greetings ----"
      
      - name: "Checkout"
        uses: actions/checkout@v4
      
      - name: "Build a Docker image from the repo"
        run:  | 
          docker build -t theoafactor/simplewebapp101 frontend/

      - name: "Log into Docker Hub"
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Push to Docker Hub"
        run: |
          docker push theoafactor/simplewebapp101 

      


